### Site info:
title: dang hai an's dev blog
tagline: Journey to craftmanship
author: Lijia Yu
email: yu@lijiayu.net
description: "Freshman21 is a Jekyll blog theme." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "Jekyll, theme, Freshman21"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://danghaian.com/blog" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: DangHaiAn1
github_username:  zyzo
# disqus_shortname: 
favicon:     "/images/favicon.ico"
aboutme: An unknown software student who's trying his best to be useful to the world # these are shown on aboutme-sidebar.
aboutme_photo: https://pbs.twimg.com/profile_images/378800000425114514/03164780ca4792aa73dba8688f64335a_400x400.jpeg # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
ShowCopyrightNotice: "False"
ShowBlogRoll: "False"
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      # Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "

### your Blogroll info, only name can shown on the page.

# Blogroll:
#    - name: 
#      href:
#      title: 


### Build settings
markdown: kramdown
highlighter: pygments
paginate: 5
