### Site info:
title: dha's dev blog
tagline: Programming explorer
author: Dang Hai An
email: danghaian168@gmail.com
description: "Dang Hai An's technical blog" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: "danghaian, zyzo, Jekyll, devblog, programming"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zyzo.github.io" # the base hostname & protocol for your site
locale: en_US

### Personal info and site tools info:
twitter_username: DangHaiAn1
github_username: zyzo
disqus_shortname: danghaian
favicon: "/images/favicon.ico"
aboutme_photo: "/images/avatar.jpeg" # your photo.

### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
ShowCopyrightNotice: "False"
ShowBlogRoll: "True"
DisplayWordLimits: 70
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
  en:
    Aboutme: "About Me"
    Archives: "Archives"
    Blogroll: "Links"
    Categories: "Categories"
    Copyright_Notice: "Copyright Notice"
    Recent_Posts: "Recent Posts"
    Tags: "Tags"
    Previous: "Older"
    Next: "Newer"
    PostedInCategories: "Posted in"
    Taggedwith: "tags : "
    PostDate: "on "

### your Blogroll info, only name can shown on the page.

Blogroll:
  - name: blog.fossasia.org
    href: http://blog.fossasia.org
    title: Open source technology community in ASIA

### Build settings
markdown: kramdown
highlighter: rouge
paginate: 10
gems: [jekyll-paginate]
